### ISSUE TITLE
Inquiry about ReMuQ dataset usage and evaluation

### ISSUE THREAD

**Issue by JUNJIE99** [luomancs/ReMuQ#1]
Hey, thank you for your great work!

I would like to confirm the usage of the ReMuQ dataset. I understand that the "question" and "img_id" in the `test.json` file form a multimodal query pair, and the "answers" represent positive candidates. During retrieval, the `open_corpus_195837.csv` provided in the links is used as the corpus.

I am seeking clarification on the discrepancy between my results, as per the settings outlined in Table 5 of the appendix, and those presented in your paper. I conducted retrieval using only text-query in the `test.json` file, and the CLIP-Q model achieved a Recall@1 of 52.08% and a Recall@5 of 59.08% from `open_corpus_195837.csv`. 
This seems to differ from the results in your Table 5 (where the paper reports a Recall@5 of 0). Therefore, I am questioning whether there might be an issue with my evaluation method. Additionally, I noticed that the corpus size mentioned in the paper is 199K, whereas the dataset I downloaded contains 195K entries. I would greatly appreciate it if you could point out any errors in my evaluation. 

Looking forward to your reply, thank you.

**Comment by luomancs** [comment]
Hi, thank you for your interest in this work

For the corpus size, 195K is correct and this is the value we mentioned in Table 1 (Knowledge corpus size of ReMuQ). Thanks for pointing this out and we will update the typo in other places in the paper. 

For the evaluation, I am surprise that you get so high performance, did you index all the corpus and how do you get the scores?

**Comment by JUNJIE99** [comment]
Thank you very much for your response!

Yes, I indexed all the corpus. I used the CLIP Text Encoder to encode the text of the query and the corpus, and then calculated the average recall of the query. I also tried using another text embedding model, it also achieved a relatively high Recall@1. 

Therefore, I would like to confirm **if it is correct to use the values in the "question" field of the`test.json`file as the query?** I found the query and positive candidate exhibit a strong semantic correlation. Here are the first two examples extracted from the `test.json` file:

```
(1)
"question": "what shapes are painted down the center of boulevard?",
"answers": {
"Blue footprints are painted down the center of Salou Boulevard.": 1
}
(2)
"question": "do most people affix their satellite on the roof of the building or on the front of the building along street - and in greater manchester, england?",
"answers": {
"Most people affix their satellite on the front of the building along Alfred street at Shaw and Crompton.": 1
}


```

**Comment by luomancs** [comment]
Hi there, first of all, sorry for my late response. Thank you for the examples and the explanation. It is correct to use the values in the question field and your process sounds the same as what I did for the CLIP baseline.
