### ISSUE TITLE
Regarding to additional code release

### ISSUE THREAD

**Issue by yeongjoonJu** [luomancs/ReMuQ#2]
First of all, thank you for your excellent work.

I wonder about your plan for additional releases, such as VL-ICT, model architecture, and checkpoints.

I'd like to take your work as a baseline for our paper.

If there are no official plans for additional code and data releases, could I receive them via email?

I would appreciate it if you could let me know your release plan!

**Comment by luomancs** [comment]
Hi, thank you for your interest in our work. yes, we would open the source in the coming weeks. keep eye on this repo and I will email when the code is released.

**Comment by yeongjoonJu** [comment]
Thank you for your answer :)

I'll look forward to your code and data release.
